using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using BepInEx;

namespace TownOfHost.Modules;

/// <summary>
/// ホストの発言だけを候補判定し、運営用Workerへ送る。
/// 違反の確定・処分は運営側で行う。
/// </summary>
internal static class ModerationRelay
{
    private const string RelayUrl = "https://toh-tm.nkzk-owo.workers.dev/";
    private const int MaxRecentMessages = 12;
    private const int MaxLogCharacters = 900000;
    private static readonly HttpClient Client = new() { Timeout = TimeSpan.FromSeconds(10) };
    private static readonly object Sync = new();
    private static readonly Queue<string> RecentChat = new();
    private static string LastReportedKey = "";
    private static DateTime LastReportedAtUtc = DateTime.MinValue;

    // 禁止語候補は運営側で最終判断する前提。ゲーム用語や短い語も候補として扱う。
    // 誤検知を含む候補のため、検知時点では処分を確定しない。
    private static readonly string[] CandidateTerms =
    {
        "(  ́,_ゝ`)プッ",
        "(  ́∀`)オマエモナー",
        "( ´,_ゝ｀)ﾌﾟｯ",
        "( ´∀｀)ｵﾏｴﾓﾅｰ",
        "( ゚д゚)、ペッ",
        "( ゚Д゚)ゴルァ",
        "( ﾟдﾟ)､ﾍﾟｯ",
        "( ﾟДﾟ)ｺﾞﾙｧ",
        "(゚д゚)ハァ?",
        "(ﾟдﾟ)ﾊｧ?",
        "114514",
        "1919",
        "420",
        "4545",
        "45451919",
        "514",
        "69",
        "69しよう",
        "69シヨウ",
        "810",
        "893",
        "\\(^o^)/",
        "\\(^o^)/オワタ",
        "ANAL",
        "Anal",
        "anal",
        "ARSEHOLE",
        "Arsehole",
        "arsehole",
        "ASS",
        "Ass",
        "ass",
        "ASSHOLE",
        "Asshole",
        "asshole",
        "BALLS",
        "Balls",
        "balls",
        "BASTARD",
        "Bastard",
        "bastard",
        "BITCH",
        "Bitch",
        "bitch",
        "BLOW JOB",
        "Blow Job",
        "blow job",
        "BLOWJOB",
        "Blowjob",
        "blowjob",
        "BOOBIES",
        "Boobies",
        "boobies",
        "BOOBS",
        "Boobs",
        "boobs",
        "BULLSHIT",
        "Bullshit",
        "bullshit",
        "COCK",
        "Cock",
        "cock",
        "CREAMPIE",
        "Creampie",
        "creampie",
        "CUM",
        "Cum",
        "cum",
        "CUMSHOT",
        "Cumshot",
        "cumshot",
        "CUNT",
        "Cunt",
        "cunt",
        "DEEPTHROAT",
        "Deepthroat",
        "deepthroat",
        "DICK",
        "Dick",
        "dick",
        "DICKHEAD",
        "Dickhead",
        "dickhead",
        "DILF",
        "Dilf",
        "dilf",
        "DOUCHE",
        "Douche",
        "douche",
        "DOUCHEBAG",
        "Douchebag",
        "douchebag",
        "DQN",
        "Dqn",
        "dqn",
        "DUMB ASS",
        "Dumb Ass",
        "dumb ass",
        "DUMBASS",
        "Dumbass",
        "dumbass",
        "EAT SHIT",
        "Eat Shit",
        "eat shit",
        "F**K",
        "f**k",
        "F*CK",
        "F*Ck",
        "f*ck",
        "FCK",
        "Fck",
        "fck",
        "FUCC",
        "Fucc",
        "fucc",
        "FUCK",
        "Fuck",
        "fuck",
        "FUCK OFF",
        "Fuck Off",
        "fuck off",
        "FUCK YOU",
        "Fuck You",
        "fuck you",
        "FUCKBOY",
        "Fuckboy",
        "fuckboy",
        "FUCKED UP",
        "Fucked Up",
        "fucked up",
        "FUCKER",
        "Fucker",
        "fucker",
        "FUCKGIRL",
        "Fuckgirl",
        "fuckgirl",
        "FUCKIN",
        "Fuckin",
        "fuckin",
        "FUCKING",
        "Fucking",
        "fucking",
        "FUK",
        "Fuk",
        "fuk",
        "GANGBANG",
        "Gangbang",
        "gangbang",
        "GARBAGE",
        "Garbage",
        "garbage",
        "GET FUCKED",
        "Get Fucked",
        "get fucked",
        "GGRKS",
        "Ggrks",
        "ggrks",
        "GO TO HELL",
        "Go To Hell",
        "go to hell",
        "GTFO",
        "Gtfo",
        "gtfo",
        "H",
        "h",
        "HANDJOB",
        "Handjob",
        "handjob",
        "HOE",
        "Hoe",
        "hoe",
        "HORNY",
        "Horny",
        "horny",
        "IDIOT",
        "Idiot",
        "idiot",
        "INCEL",
        "Incel",
        "incel",
        "JERK OFF",
        "Jerk Off",
        "jerk off",
        "JERKOFF",
        "Jerkoff",
        "jerkoff",
        "JIZZ",
        "Jizz",
        "jizz",
        "KILL YOURSELF",
        "Kill Yourself",
        "kill yourself",
        "KYS",
        "Kys",
        "kys",
        "LMAO",
        "Lmao",
        "lmao",
        "LMFAO",
        "Lmfao",
        "lmfao",
        "LOSER",
        "Loser",
        "loser",
        "M9(^Д^)",
        "m9(^Д^)",
        "m9(^д^)",
        "MASTURBATE",
        "Masturbate",
        "masturbate",
        "MILF",
        "Milf",
        "milf",
        "MORON",
        "Moron",
        "moron",
        "MOTHER FUCKER",
        "Mother Fucker",
        "mother fucker",
        "MOTHERFUCKER",
        "Motherfucker",
        "motherfucker",
        "MOTHERFUCKING",
        "Motherfucking",
        "motherfucking",
        "NUTS",
        "Nuts",
        "nuts",
        "ORGASM",
        "Orgasm",
        "orgasm",
        "ORZ",
        "Orz",
        "orz",
        "PENIS",
        "Penis",
        "penis",
        "PIECE OF GARBAGE",
        "Piece Of Garbage",
        "piece of garbage",
        "PIECE OF SHIT",
        "Piece Of Shit",
        "piece of shit",
        "PIECEOFSHIT",
        "Pieceofshit",
        "pieceofshit",
        "PISS",
        "Piss",
        "piss",
        "PISS OFF",
        "Piss Off",
        "piss off",
        "PISSHEAD",
        "Pisshead",
        "pisshead",
        "PUSSY",
        "Pussy",
        "pussy",
        "RAPE",
        "Rape",
        "rape",
        "RAPIST",
        "Rapist",
        "rapist",
        "RETARD",
        "Retard",
        "RETARDED",
        "Retarded",
        "ROMれ",
        "Romれ",
        "romれ",
        "ROMレ",
        "SCUMBAG",
        "Scumbag",
        "scumbag",
        "SEMEN",
        "Semen",
        "semen",
        "SEX",
        "Sex",
        "sex",
        "SHINE",
        "Shine",
        "shine",
        "SHIT",
        "Shit",
        "shit",
        "SHITHEAD",
        "Shithead",
        "shithead",
        "SIMP",
        "Simp",
        "simp",
        "SINE",
        "Sine",
        "sine",
        "SLUT",
        "Slut",
        "slut",
        "SON OF A BITCH",
        "Son Of A Bitch",
        "son of a bitch",
        "SONOFABITCH",
        "Sonofabitch",
        "sonofabitch",
        "STFU",
        "Stfu",
        "stfu",
        "STUPID",
        "Stupid",
        "stupid",
        "SUCK IT",
        "Suck It",
        "suck it",
        "SUCK MY DICK",
        "Suck My Dick",
        "suck my dick",
        "THOT",
        "Thot",
        "thot",
        "TITS",
        "Tits",
        "tits",
        "TRASH",
        "Trash",
        "trash",
        "VAGINA",
        "Vagina",
        "vagina",
        "VIRGIN",
        "Virgin",
        "virgin",
        "WANK",
        "Wank",
        "wank",
        "WANKER",
        "Wanker",
        "wanker",
        "WHAT THE FUCK",
        "What The Fuck",
        "what the fuck",
        "WHORE",
        "Whore",
        "whore",
        "WTF",
        "Wtf",
        "wtf",
        "WWW",
        "Www",
        "www",
        "WWWW",
        "Wwww",
        "wwww",
        "あくしろよ",
        "あっー",
        "あっー！",
        "あなる",
        "あほ",
        "あほか",
        "あほんだら",
        "いいよ!こいよ!",
        "いいよ！こいよ！",
        "いい男",
        "いきすぎ",
        "いきすぎぃ",
        "いきってんな",
        "いきり",
        "いきり野郎",
        "いく",
        "いくいく",
        "いっちゃう",
        "うざい",
        "うせろ",
        "うぜえ",
        "うほっ",
        "うるせえ",
        "うるせー",
        "うんこ",
        "うんこまみれ",
        "うんこ食え",
        "うんち",
        "えっち",
        "えろ",
        "えろい",
        "えろ動画",
        "おしっこ",
        "おたくきもい",
        "おちんちん",
        "おっすお願いしまーす",
        "おっぱい",
        "おつ",
        "おなにー",
        "おなら",
        "おまいう",
        "おまえもなー",
        "おまんこ",
        "おま環",
        "おわこん",
        "おわた",
        "おチンチン",
        "お前が始めた物語だろ",
        "お前が言うな",
        "お前じゃい",
        "お前なんかいらない",
        "お前のことが好きだったんだよ",
        "お前の母ちゃんでべそ",
        "お前はくず",
        "お前はごみ",
        "お前はごみ以下",
        "お前はクズ",
        "お前はゴミ",
        "お前はゴミ以下",
        "お前ら",
        "お前消えるのか",
        "お尻",
        "お気持ち表明",
        "かす",
        "かす人間",
        "かす野郎",
        "がいじ",
        "がいじむーぶ",
        "がき",
        "きしょい",
        "きちがい",
        "きっず",
        "きとう",
        "きもい",
        "きもおた",
        "きもをた",
        "きんたま",
        "くず",
        "くず人間",
        "くず野郎",
        "くそ",
        "くそが",
        "くそがき",
        "くそげー",
        "くそじじい",
        "くそっ",
        "くそったれ",
        "くそばばあ",
        "くそまみれ",
        "くそみそてくにっく",
        "くそみそテクニック",
        "くそみたい",
        "くそりぷ",
        "くそりぷ乙",
        "くそわろた",
        "くそガキ",
        "くそ女",
        "くそ男",
        "くそ野郎",
        "くそ野郎が",
        "くそ雑魚",
        "くそ食らえ",
        "くたばれ",
        "くびつれ",
        "くんに",
        "ぐぐれかす",
        "けつ",
        "けつあな",
        "けつ穴",
        "げろ",
        "こ↑こ↓",
        "こうもん",
        "こみゅ障",
        "ころしてやる",
        "ころす",
        "ころすぞ",
        "こんちくしょう",
        "ごみ",
        "ごみかす",
        "ごみげー",
        "ごみみたい",
        "ごみカス",
        "ざこ",
        "ざこ乙",
        "ざまぁ",
        "ざまあ",
        "ざーめん",
        "しこしこ",
        "しこる",
        "しね",
        "しねや",
        "しねよ",
        "しゃぶれ",
        "しょじょ",
        "しょんべん",
        "しりあな",
        "せっくす",
        "せふれ",
        "そうだよ",
        "そうだよ(便乗)",
        "そうだよ（便乗）",
        "それな",
        "それは草",
        "たひね",
        "たひれ",
        "たまきん",
        "ちくしょう",
        "ちくしょー",
        "ちくび",
        "ちんこ",
        "ちんちん",
        "ちんぽ",
        "ちんぽこ",
        "ちん棒",
        "ちーず牛丼",
        "ちーず牛丼顔",
        "ちー牛",
        "ちー牛顔",
        "つれ",
        "てこき",
        "てらわろす",
        "でぶ",
        "どうてい",
        "どきゅん",
        "どじ",
        "どるおた",
        "なめてんのか",
        "なめんな",
        "なんJ",
        "なんj",
        "なんでやねん",
        "なんＪ",
        "ぬわああああん疲れたもおおおおん",
        "のぞき",
        "のろま",
        "はい嘘",
        "はい解散",
        "はい論破",
        "はげ",
        "ばぁか",
        "ばか",
        "ばかか",
        "ばか野郎",
        "ばーか",
        "ぱいずり",
        "ぱおん",
        "ぱぱ活",
        "ぱんちら",
        "ぱんつ",
        "ぱんてぃー",
        "びっち",
        "びりー兄貴",
        "ぴえん",
        "ふぁっ",
        "ふぁっ！？",
        "ふぇら",
        "ふぇらちお",
        "ふざけんな",
        "ふざけんなよ",
        "ぶさいく",
        "ぶす",
        "ぶた",
        "ぶちのめす",
        "ぶち殺す",
        "ぶち殺すぞ",
        "ぶっ殺してやる",
        "ぶっ殺す",
        "ぶっ潰してやる",
        "ぶっ潰す",
        "ぶっ飛ばす",
        "ぶらじゃー",
        "ぶん殴る",
        "ぶーめらん",
        "ぶーめらん乙",
        "へ",
        "へたくそ",
        "ほも",
        "ほもぉ",
        "ほもがき",
        "ぼっき",
        "ぼっち",
        "ぽんこつ",
        "まずうちさぁ、屋上あんだけど",
        "まぬけ",
        "ままに言いつけるぞ",
        "まんぐり返し",
        "まんこ",
        "まんちょ",
        "まん汁",
        "むかつく",
        "めしうま",
        "めしまず",
        "もう終わりだよこの国",
        "もう許さねえからなぁ?",
        "もう許さねえからなぁ？",
        "やばたにえん",
        "やらせろ",
        "やらないか",
        "やりたい",
        "やりちん",
        "やりますねぇ",
        "やりますねぇ!",
        "やりますねぇ！",
        "やりまん",
        "ゆとり",
        "ゆとり乙",
        "りあ充爆発しろ",
        "れいぷ",
        "れすりんぐしりーず",
        "わろす",
        "わろた",
        "わろりんぬ",
        "わんちゃん",
        "ん?今何でもするって言ったよね",
        "んあっー",
        "んご",
        "んごごご",
        "んごねぇ",
        "んごｗ",
        "んごｗｗｗ",
        "ん？今何でもするって言ったよね",
        "アクシロヨ",
        "アッー",
        "アッー!",
        "アッー！",
        "アナル",
        "アホ",
        "アホか",
        "アホカ",
        "アホンダラ",
        "イく",
        "イイヨ！コイヨ！",
        "イイ男",
        "イキってんな",
        "イキスギ",
        "イキスギィ",
        "イキッテンナ",
        "イキリ",
        "イキリ野郎",
        "イク",
        "イクイク",
        "イッチャウ",
        "ウザイ",
        "ウセロ",
        "ウゼエ",
        "ウホッ",
        "ウルセエ",
        "ウルセー",
        "ウンコ",
        "ウンコマミレ",
        "ウンコ食エ",
        "ウンチ",
        "エッチ",
        "エロ",
        "エロい",
        "エロイ",
        "エロ動画",
        "オシッコ",
        "オタクきもい",
        "オタクキモイ",
        "オチンチン",
        "オッスお願いしまーす",
        "オッスオ願イシマース",
        "オッパイ",
        "オツ",
        "オナニー",
        "オナラ",
        "オマイウ",
        "オマエモナー",
        "オマンコ",
        "オマ環",
        "オワコン",
        "オワタ",
        "オ前ガ始メタ物語ダロ",
        "オ前ガ言ウナ",
        "オ前ジャイ",
        "オ前ナンカイラナイ",
        "オ前ノコトガ好キダッタンダヨ",
        "オ前ノ母チャンデベソ",
        "オ前ハクズ",
        "オ前ハゴミ",
        "オ前ハゴミ以下",
        "オ前ラ",
        "オ前消エルノカ",
        "オ尻",
        "オ気持チ表明",
        "カス",
        "カス人間",
        "カス野郎",
        "ガイジムーブ",
        "ガキ",
        "キショい",
        "キショイ",
        "キチガイ",
        "キッズ",
        "キトウ",
        "キモい",
        "キモイ",
        "キモオタ",
        "キモヲタ",
        "キンタマ",
        "クズ",
        "クズ人間",
        "クズ野郎",
        "クソ",
        "クソが",
        "クソったれ",
        "クソみたい",
        "クソガ",
        "クソガキ",
        "クソゲー",
        "クソジジイ",
        "クソッ",
        "クソッタレ",
        "クソババア",
        "クソマミレ",
        "クソミソテクニック",
        "クソミタイ",
        "クソリプ",
        "クソリプ乙",
        "クソワロタ",
        "クソ女",
        "クソ男",
        "クソ野郎",
        "クソ野郎が",
        "クソ野郎ガ",
        "クソ雑魚",
        "クソ食らえ",
        "クソ食ラエ",
        "クタバレ",
        "クビツレ",
        "クンニ",
        "ググれカス",
        "ググレカス",
        "ケツ",
        "ケツアナ",
        "ケツ穴",
        "ゲロ",
        "コ↑コ↓",
        "コウモン",
        "コミュ障",
        "コロシテヤル",
        "コロス",
        "コロスゾ",
        "コンチクショウ",
        "ゴミ",
        "ゴミみたい",
        "ゴミカス",
        "ゴミゲー",
        "ゴミミタイ",
        "ザコ",
        "ザコ乙",
        "ザマァ",
        "ザマア",
        "ザーメン",
        "シコる",
        "シコシコ",
        "シコル",
        "シネ",
        "シネヤ",
        "シネヨ",
        "シャブレ",
        "ショジョ",
        "ションベン",
        "シリアナ",
        "セックス",
        "セフレ",
        "ソウダヨ",
        "ソウダヨ（便乗）",
        "ソレナ",
        "ソレハ草",
        "タヒ",
        "タヒね",
        "タヒれ",
        "タヒネ",
        "タヒレ",
        "タマキン",
        "チクショウ",
        "チクショー",
        "チクビ",
        "チンコ",
        "チンチン",
        "チンポ",
        "チンポコ",
        "チン棒",
        "チーズ牛丼",
        "チーズ牛丼顔",
        "チー牛",
        "チー牛顔",
        "ツレ",
        "テコキ",
        "テラワロス",
        "デブ",
        "ドウテイ",
        "ドキュン",
        "ドジ",
        "ドルオタ",
        "ナメテンノカ",
        "ナメンナ",
        "ナンJ",
        "ナンデヤネン",
        "ヌワアアアアン疲レタモオオオオン",
        "ノゾキ",
        "ノロマ",
        "ハイ嘘",
        "ハイ解散",
        "ハイ論破",
        "ハゲ",
        "バァカ",
        "バカ",
        "バカか",
        "バカカ",
        "バカ野郎",
        "バーカ",
        "パイズリ",
        "パオン",
        "パパ活",
        "パンチラ",
        "パンツ",
        "パンティー",
        "ビッチ",
        "ビリー兄貴",
        "ピエン",
        "ファッ",
        "ファッ!?",
        "ファッ！？",
        "フェラ",
        "フェラチオ",
        "フザケンナ",
        "フザケンナヨ",
        "ブサイク",
        "ブス",
        "ブタ",
        "ブチノメス",
        "ブチ殺ス",
        "ブチ殺スゾ",
        "ブッ殺シテヤル",
        "ブッ殺ス",
        "ブッ潰シテヤル",
        "ブッ潰ス",
        "ブッ飛バス",
        "ブラジャー",
        "ブン殴ル",
        "ブーメラン",
        "ブーメラン乙",
        "ヘ",
        "ヘタクソ",
        "ボッキ",
        "ボッチ",
        "ポンコツ",
        "マズウチサァ、屋上アンダケド",
        "マヌケ",
        "ママに言いつけるぞ",
        "ママニ言イツケルゾ",
        "マングリ返シ",
        "マンコ",
        "マンチョ",
        "マン汁",
        "ムカツク",
        "メシウマ",
        "メシマズ",
        "モウ終ワリダヨコノ国",
        "モウ許サネエカラナァ？",
        "ヤらせろ",
        "ヤバタニエン",
        "ヤラセロ",
        "ヤラナイカ",
        "ヤリタイ",
        "ヤリチン",
        "ヤリマスネェ",
        "ヤリマスネェ！",
        "ヤリマン",
        "ユトリ",
        "ユトリ乙",
        "リア充爆発しろ",
        "リア充爆発シロ",
        "レイプ",
        "レスリングシリーズ",
        "ワロス",
        "ワロタ",
        "ワロリンヌ",
        "ワンチャン",
        "ンアッー",
        "ンゴ",
        "ンゴw",
        "ンゴwww",
        "ンゴねぇ",
        "ンゴゴゴ",
        "ンゴネェ",
        "ンゴｗ",
        "ンゴｗｗｗ",
        "ン？今何デモスルッテ言ッタヨネ",
        "下手くそ",
        "下手すぎ",
        "下手クソ",
        "下手スギ",
        "中出し",
        "中出シ",
        "乙",
        "乙w",
        "乙ｗ",
        "乳房",
        "乳輪",
        "乳首",
        "乳首見せろ",
        "乳首見セロ",
        "亀頭",
        "人間のくず",
        "人間のクズ",
        "人間ノクズ",
        "便器",
        "兄貴",
        "全裸",
        "処女",
        "利敵",
        "効いてて草",
        "効いてる効いてる",
        "効イテテ草",
        "効イテル効イテル",
        "勃起",
        "半年ROMってろ",
        "半年Romってろ",
        "半年romってろ",
        "半年ROMれ",
        "半年Romれ",
        "半年romれ",
        "半年ROMッテロ",
        "半年ROMレ",
        "半年ＲＯＭってろ",
        "半年ＲＯＭれ",
        "厨房",
        "吊ってこい",
        "吊っとけ",
        "吊る",
        "吊るぞ",
        "吊れ",
        "吊ッテコイ",
        "吊ットケ",
        "吊ル",
        "吊ルゾ",
        "吊レ",
        "吹いた",
        "吹イタ",
        "咥えろ",
        "咥エロ",
        "嘔吐",
        "嘘乙",
        "嘘松",
        "地雷",
        "基地外",
        "売女",
        "売春",
        "変態",
        "変態ぷれい",
        "変態プレイ",
        "変態野郎",
        "外出し",
        "外出シ",
        "大便",
        "大草原",
        "失せろ",
        "失せろよ",
        "失セロ",
        "失セロヨ",
        "女性器",
        "奴隷にして",
        "奴隷ニシテ",
        "妊娠させる",
        "妊娠サセル",
        "娼婦",
        "孕ませる",
        "孕む",
        "孕マセル",
        "孕ム",
        "射精",
        "尊い",
        "尊イ",
        "小便",
        "尻",
        "尻穴",
        "尿",
        "屁",
        "屁こき",
        "屁コキ",
        "弱すぎ",
        "弱スギ",
        "強姦",
        "役立たず",
        "役立タズ",
        "性交",
        "性器",
        "性奴隷",
        "性行為",
        "情弱",
        "情弱すぎ",
        "情弱スギ",
        "情弱乙",
        "戦犯",
        "手こき",
        "手コキ",
        "抜いて",
        "抜く",
        "抜け",
        "抜イテ",
        "抜ク",
        "抜ケ",
        "抱かせろ",
        "抱カセロ",
        "援交",
        "援助交際",
        "撮り鉄",
        "撮リ鉄",
        "最低",
        "最悪",
        "枕がでかい",
        "枕ガデカイ",
        "死 ね",
        "死.ね",
        "死.ネ",
        "死　ね",
        "死　ネ",
        "死ね",
        "死ねかす",
        "死ねごみ",
        "死ねばいい",
        "死ねばいいのに",
        "死ねや",
        "死ねよ",
        "死ねカス",
        "死ねゴミ",
        "死んじまえ",
        "死んだほうがいい",
        "死んだ方がいい",
        "死んで",
        "死んでくれ",
        "死んどけ",
        "死ネ",
        "死ネカス",
        "死ネゴミ",
        "死ネバイイ",
        "死ネバイイノニ",
        "死ネヤ",
        "死ネヨ",
        "死ンジマエ",
        "死ンダホウガイイ",
        "死ンダ方ガイイ",
        "死ンデ",
        "死ンデクレ",
        "死ンドケ",
        "死ﾈ",
        "殴るぞ",
        "殴ルゾ",
        "殺してやる",
        "殺してやるからな",
        "殺す",
        "殺すぞ",
        "殺シテヤル",
        "殺シテヤルカラナ",
        "殺ス",
        "殺スゾ",
        "氏ね",
        "氏ねや",
        "氏ネ",
        "氏ネヤ",
        "消えてなくなれ",
        "消えろ",
        "消えろよ",
        "消え失せろ",
        "消してやる",
        "消エテナクナレ",
        "消エロ",
        "消エロヨ",
        "消エ失セロ",
        "消シテヤル",
        "消防",
        "涙拭けよ",
        "涙拭ケヨ",
        "涙目",
        "淫ら",
        "淫ラ",
        "淫乱",
        "淫夢",
        "潮吹き",
        "潮吹キ",
        "無理げー",
        "無理ゲー",
        "無能",
        "爆発しろ",
        "爆発シロ",
        "犯して",
        "犯す",
        "犯シテ",
        "犯ス",
        "玉袋",
        "珍棒",
        "生きてる価値ない",
        "生きる価値ない",
        "生キテル価値ナイ",
        "生キル価値ナイ",
        "男性器",
        "痴漢",
        "発情",
        "盗撮",
        "目くそ",
        "目クソ",
        "真夏の夜の淫夢",
        "真夏ノ夜ノ淫夢",
        "知らんけど",
        "知ランケド",
        "知恵遅レ",
        "神げー（笑）",
        "神ゲー(笑)",
        "神ゲー（笑）",
        "童貞",
        "精子",
        "精液",
        "糞",
        "糞げー",
        "糞りぷ",
        "糞ゲー",
        "糞リプ",
        "糞便",
        "糞尿",
        "糞食い",
        "糞食らえ",
        "糞食イ",
        "糞食ラエ",
        "素股",
        "終わってる",
        "終わりだよこのげーむ",
        "終わりだよこのゲーム",
        "終ワッテル",
        "終ワリダヨコノゲーム",
        "老害",
        "耳くそ",
        "耳クソ",
        "肉便器",
        "肉奴隷",
        "肛門",
        "能なし",
        "能ナシ",
        "能無し",
        "能無シ",
        "脱がせろ",
        "脱げ",
        "脱ガセロ",
        "脱ゲ",
        "脳みそお花畑",
        "脳ミソオ花畑",
        "脳筋",
        "腐女子",
        "腹筋崩壊",
        "膣",
        "膣内",
        "膣口",
        "膣痙攣",
        "自己紹介乙",
        "自慰",
        "自慰行為",
        "自殺しろ",
        "自殺しろよ",
        "自殺シロ",
        "自殺シロヨ",
        "舐めてんのか",
        "舐メテンノカ",
        "草",
        "草ぁ",
        "草ぁ！",
        "草なんだ",
        "草ァ",
        "草ァ!",
        "草ァ！",
        "草ナンダ",
        "草不可避",
        "草生える",
        "草生エル",
        "薔薇族",
        "袋",
        "裸",
        "解散",
        "許してください何でもしますから",
        "許シテクダサイ何デモシマスカラ",
        "詰み",
        "詰んだ",
        "詰ミ",
        "詰ンダ",
        "調子乗んな",
        "調子乗ンナ",
        "論破",
        "豚",
        "豚おた",
        "豚オタ",
        "買春",
        "輪姦",
        "逝く",
        "逝け",
        "逝けよ",
        "逝ってよし",
        "逝ってヨシ",
        "逝ク",
        "逝ケ",
        "逝ケヨ",
        "逝ッテヨシ",
        "醜い",
        "醜イ",
        "野獣先輩",
        "金玉",
        "釣り乙",
        "釣り宣言",
        "釣リ乙",
        "釣リ宣言",
        "鉄おた",
        "鉄オタ",
        "間抜け",
        "間抜ケ",
        "阿呆",
        "阿部さん",
        "阿部サン",
        "陰きゃ",
        "陰きゃ乙",
        "陰キャ",
        "陰キャ乙",
        "陰茎",
        "陰部",
        "陽きゃ（笑）",
        "陽キャ(笑)",
        "陽キャ（笑）",
        "雑魚",
        "雑魚すぎ",
        "雑魚スギ",
        "雑魚乙",
        "非りあ",
        "非りあ充",
        "非リア",
        "非リア充",
        "非処女",
        "頭おかしい",
        "頭オカシイ",
        "頭大丈夫か",
        "頭大丈夫カ",
        "頭悪い",
        "頭悪イ",
        "頭沸いてる",
        "頭沸イテル",
        "頭腐ってる",
        "頭腐ッテル",
        "顔真っ赤",
        "顔真ッ赤",
        "顔面草まみれ",
        "顔面草マミレ",
        "風俗嬢",
        "首つれ",
        "首ツレ",
        "首吊ってこい",
        "首吊る",
        "首吊れ",
        "首吊れよ",
        "首吊ッテコイ",
        "首吊ル",
        "首吊レ",
        "首吊レヨ",
        "香ばしい",
        "香ばしい奴",
        "香バシイ",
        "香バシイ奴",
        "香具師",
        "馬鹿",
        "馬鹿か",
        "馬鹿カ",
        "馬鹿野郎",
        "黙ってろ",
        "黙っとけ",
        "黙れ",
        "黙ッテロ",
        "黙ットケ",
        "黙レ",
        "鼻くそ",
        "鼻クソ",
        "＼(^O^)／",
        "＼(^o^)／",
        "＼(^O^)／ｵﾜﾀ",
        "＼(^o^)／ｵﾜﾀ",
        "＼（＾ｏ＾）／",
        "＼（＾ｏ＾）／ｵﾜﾀ",
        "ａｎａｌ",
        "ａｒｓｅｈｏｌｅ",
        "ａｓｓ",
        "ａｓｓｈｏｌｅ",
        "ｂａｌｌｓ",
        "ｂａｓｔａｒｄ",
        "ＢＩＴＣＨ",
        "ｂｉｔｃｈ",
        "ｂｌｏｗ ｊｏｂ",
        "ｂｌｏｗｊｏｂ",
        "ｂｏｏｂｉｅｓ",
        "ｂｏｏｂｓ",
        "ｂｕｌｌｓｈｉｔ",
        "ｃｏｃｋ",
        "ｃｒｅａｍｐｉｅ",
        "ｃｕｍ",
        "ｃｕｍｓｈｏｔ",
        "ｃｕｎｔ",
        "ｄｅｅｐｔｈｒｏａｔ",
        "ｄｉｃｋ",
        "ｄｉｃｋｈｅａｄ",
        "ＤＩＬＦ",
        "ｄｏｕｃｈｅ",
        "ｄｏｕｃｈｅｂａｇ",
        "ＤＱＮ",
        "ｄｕｍｂ ａｓｓ",
        "ｄｕｍｂａｓｓ",
        "ｅａｔ ｓｈｉｔ",
        "ｆ＊＊ｋ",
        "ｆ＊ｃｋ",
        "ｆｃｋ",
        "ｆｕｃｃ",
        "ＦＵＣＫ",
        "Ｆｕｃｋ",
        "ｆｕｃｋ",
        "ｆｕｃｋ ｏｆｆ",
        "ｆｕｃｋ ｙｏｕ",
        "ｆｕｃｋｂｏｙ",
        "ｆｕｃｋｅｄ ｕｐ",
        "ｆｕｃｋｅｒ",
        "ｆｕｃｋｇｉｒｌ",
        "ｆｕｃｋｉｎ",
        "ｆｕｃｋｉｎｇ",
        "ｆｕｋ",
        "ｇａｎｇｂａｎｇ",
        "ｇａｒｂａｇｅ",
        "ｇｅｔ ｆｕｃｋｅｄ",
        "ｇｇｒｋｓ",
        "ｇｏ ｔｏ ｈｅｌｌ",
        "ｇｔｆｏ",
        "Ｈ",
        "ｈ",
        "ｈａｎｄｊｏｂ",
        "ｈｏｅ",
        "ｈｏｒｎｙ",
        "ｉｄｉｏｔ",
        "ｉｎｃｅｌ",
        "ｊｅｒｋ ｏｆｆ",
        "ｊｅｒｋｏｆｆ",
        "ｊｉｚｚ",
        "ｋｉｌｌ ｙｏｕｒｓｅｌｆ",
        "ｋｙｓ",
        "ｌｍａｏ",
        "ｌｍｆａｏ",
        "ｌｏｓｅｒ",
        "ｍ９（＾Д＾）",
        "ｍａｓｔｕｒｂａｔｅ",
        "ＭＩＬＦ",
        "ｍｏｒｏｎ",
        "ｍｏｔｈｅｒ ｆｕｃｋｅｒ",
        "ｍｏｔｈｅｒｆｕｃｋｅｒ",
        "ｍｏｔｈｅｒｆｕｃｋｉｎｇ",
        "ｎｕｔｓ",
        "ｏｒｇａｓｍ",
        "ｏｒｚ",
        "ｐｅｎｉｓ",
        "ｐｉｅｃｅ ｏｆ ｇａｒｂａｇｅ",
        "ｐｉｅｃｅ ｏｆ ｓｈｉｔ",
        "ｐｉｅｃｅｏｆｓｈｉｔ",
        "ｐｉｓｓ",
        "ｐｉｓｓ ｏｆｆ",
        "ｐｉｓｓｈｅａｄ",
        "ｐｕｓｓｙ",
        "ｒａｐｅ",
        "ｒａｐｉｓｔ",
        "ｒｅｔａｒｄ",
        "ｒｅｔａｒｄｅｄ",
        "ＲＯＭれ",
        "ｓｃｕｍｂａｇ",
        "ｓｅｍｅｎ",
        "ＳＥＸ",
        "ｓｅｘ",
        "ｓｈｉｎｅ",
        "ＳＨＩＴ",
        "Ｓｈｉｔ",
        "ｓｈｉｔ",
        "ｓｈｉｔｈｅａｄ",
        "ｓｉｍｐ",
        "ｓｉｎｅ",
        "ｓｌｕｔ",
        "ｓｏｎ ｏｆ ａ ｂｉｔｃｈ",
        "ｓｏｎｏｆａｂｉｔｃｈ",
        "ｓｔｆｕ",
        "ｓｔｕｐｉｄ",
        "ｓｕｃｋ ｉｔ",
        "ｓｕｃｋ ｍｙ ｄｉｃｋ",
        "ｔｈｏｔ",
        "ｔｉｔｓ",
        "ｔｒａｓｈ",
        "ｖａｇｉｎａ",
        "ｖｉｒｇｉｎ",
        "ｗａｎｋ",
        "ｗａｎｋｅｒ",
        "ｗｈａｔ ｔｈｅ ｆｕｃｋ",
        "ｗｈｏｒｅ",
        "ｗｔｆ",
        "ｗｗｗ",
        "ＷＷＷＷ",
        "ｱｯｰ",
        "ﾀﾋ",
        "ﾀﾋね",
        "ﾀﾋネ",
        "ﾜﾛﾀ",
        "リョナ",
        "拘束プレイ",
        "おしがま",
        "NTR",
        "ローション",
        "お”っ",
        "メスイキ",
        "メスガキ",
        "メス堕ち",
        "BL",
        "GL",
        "NL",
        "ケツマンコ",
    };

    public static void ObserveChat(PlayerControl sender, string text)
    {
        if (AmongUsClient.Instance == null || !AmongUsClient.Instance.AmHost) return;
        if (sender == null || PlayerControl.LocalPlayer == null) return;
        if (sender.PlayerId != PlayerControl.LocalPlayer.PlayerId) return;
        if (string.IsNullOrWhiteSpace(text)) return;

        var cleanText = text.RemoveHtmlTags();
        var name = sender.Data?.PlayerName ?? "不明なホスト";
        var line = $"{name}: {cleanText}";

        lock (Sync)
        {
            RecentChat.Enqueue(line);
            while (RecentChat.Count > MaxRecentMessages) RecentChat.Dequeue();
        }

        var normalized = Normalize(cleanText);
        var matched = CandidateTerms.FirstOrDefault(term => normalized.Contains(Normalize(term)));
        if (matched == null) return;

        // ChatCommands / RpcSendChat / RPCHandler の複数経路から同じ発言が届くため、
        // 同一ホスト・同一本文の短時間重複送信を防ぐ。
        var reportKey = $"{sender.PlayerId}:{normalized}";
        lock (Sync)
        {
            var now = DateTime.UtcNow;
            if (reportKey == LastReportedKey && now - LastReportedAtUtc < TimeSpan.FromSeconds(3))
                return;
            LastReportedKey = reportKey;
            LastReportedAtUtc = now;
        }

        Logger.Info($"候補語を検知: {name}: {cleanText} ({matched})", "ModerationRelay");

        var payload = new Dictionary<string, object>
        {
            ["isHost"] = true,
            ["hostName"] = name,
            ["friendCode"] = sender.GetClient()?.FriendCode ?? "不明",
            ["roomCode"] = GetRoomCode(),
            ["reason"] = $"候補語を検出: {matched}",
            ["message"] = cleanText,
            ["recentChat"] = GetRecentChat(),
            ["logText"] = ReadLogTail()
        };

        _ = SendAsync(payload);
    }

    private static string Normalize(string value)
        => new string(value.Where(c => !char.IsWhiteSpace(c) && !char.IsPunctuation(c)).ToArray())
            .ToLowerInvariant();

    private static string GetRecentChat()
    {
        lock (Sync) return string.Join("\n", RecentChat);
    }

    private static string GetRoomCode()
    {
        try { return InnerNet.GameCode.IntToGameName(AmongUsClient.Instance.GameId); }
        catch { return "不明"; }
    }

    private static string ReadLogTail()
    {
        var candidates = new[]
        {
            // Among Us.exe と同じフォルダにある BepInEx の標準ログを最優先する。
            Path.Combine(Paths.GameRootPath, "BepInEx", "LogOutput.log"),
            Path.Combine(Paths.BepInExRootPath, "LogOutput.log"),
            Path.Combine(Paths.GameRootPath, "LogOutput.log"),
            Path.Combine(Main.BaseDirectory, "LogOutput.log"),
            Path.Combine(Environment.CurrentDirectory, "BepInEx", "LogOutput.log")
        };

        foreach (var path in candidates.Distinct())
        {
            try
            {
                if (!File.Exists(path)) continue;
                // BepInExが書き込み中でも読めるよう、共有読み取りを指定する。
                using var stream = new FileStream(
                    path,
                    FileMode.Open,
                    FileAccess.Read,
                    FileShare.ReadWrite | FileShare.Delete);
                using var reader = new StreamReader(stream, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
                var text = reader.ReadToEnd();
                return text.Length <= MaxLogCharacters
                    ? text
                    : text[^MaxLogCharacters..];
            }
            catch (Exception ex)
            {
                Logger.Warn($"ログ読み取り失敗: {path} ({ex.GetType().Name})", "ModerationRelay");
            }
        }

        Logger.Warn($"ログ候補が見つかりません: {string.Join(" | ", candidates)}", "ModerationRelay");
        return "LogOutput.logを読み取れませんでした。";
    }

    private static async Task SendAsync(Dictionary<string, object> payload)
    {
        try
        {
            using var content = new StringContent(
                JsonSerializer.Serialize(payload),
                Encoding.UTF8,
                "application/json");
            using var response = await Client.PostAsync(RelayUrl, content);
            var responseBody = await response.Content.ReadAsStringAsync();
            if (!response.IsSuccessStatusCode)
                Logger.Warn($"Moderation relay failed: {(int)response.StatusCode} {responseBody}", "ModerationRelay");
            else
                Logger.Info($"Moderation relay sent: {(int)response.StatusCode}", "ModerationRelay");
        }
        catch (Exception ex)
        {
            Logger.Exception(ex, "ModerationRelay");
        }
    }
}
